---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: update yum repo
      yum:
        update_cache: yes

    - name: ensure wireshark is in the latest version
      yum:
        name: wireshark
        state: latest

- name: update lb and db server
  hosts: lb, db
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is at latest version
      apt:
        name: wireshark
        state: latest

- name: create directory, file and set timezone on all servers
  hosts: all
  become: yes
  tasks:
    - name: create directory
      file:
        path: /home/sample
        state: directory

    - name: create file
      file:
        path: /home/sample/ansible.txt
        state: touch

    - name: set timezone
      timezone:
        name: Africa/Lagos

- name: Run Command
  hosts: all
  tasks:
    - name: run echo
      command: echo "Tunji DevOps"
