pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "building stage"'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'echo "testing stage"'
                }
            }
        }
        stage('Package') {
            steps {
                script {
                    sh 'echo "packaging stage"'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'echo "deploying stage"'
                }
            }
        }
        stage('CleanUp') {
            steps {
                script {
                    sh 'echo "cleaning stage"'
                }
            }
        }
    }
}