pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "building stage"'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'echo "testing stage"'
                }
            }
        }
    }
}