---
# tasks file for webserver

- name: install and configure webservers
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/Tunji-L/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html /var/www/

- name: remove welcome page
  become: yes
  ansible.builtin.file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: start service if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: yes

- name: recursively remove /var/www/html/html
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
