# ---
#- hosts: all
#- name: deploy common playbook
#  import_playbook: ../static-assignments/common.yml
# ----------------------------------------------------
# - hosts: all
# - name: deploy common-del playbook
#   import_playbook: ../static-assignments/common-del.yml
# ----------------------------------------------

# - hosts: all
# - import_playbook: ../static-assignments/common.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml
# ------------------------------------------------------
---
- name: deploy common playbook
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- name: Include env-var files
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: webserver file
  import_playbook: ../static-assignments/uat-webservers.yml

- name: Load Balancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
 
- name: database
  import_playbook: ../static-assignments/database.yml
