---
#- hosts: all
#- name: deploy common playbook
#  import_playbook: ../static-assignments/common.yml

- hosts: all
- name: deploy common-del playbook
  import_playbook: ../static-assignments/common-del.yml
